### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [30]:
# Lista di numeri sommati a loro stessi due volte

num_list = [1,2,3,4,5]
new_numlist1 = []

for n in num_list:
    new_numlist1.append(n + n + n)

new_numlist1

# Lista di numeri al quadrato

new_numlist2 = []

for n in num_list:
    new_numlist2.append(n*n)

new_numlist2

# Lista di numeri sommati a se stessi, elevati al quadrato e a cui si sottrae il numero di partenza

new_numlist3=[]

for n in num_list:
    new_numlist3.append(((n + n) * (n + n)) - n)

new_numlist3

# L'ultima lista realizzata con la list comprehension

new_numlist4 = [(( n + n) * (n + n) - n) for n in num_list]

new_numlist4 

[3, 14, 33, 60, 95]

### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [49]:
import numpy as np

# Creo una lista per poi generare un vettore

vectorlist = [1,2,3,5,7]

prime_array = np.array(vectorlist)

prime_array

# Trovo la lunghezza del vettore coi due metodi

print(len(prime_array))

print(prime_array.size)

print(prime_array.dtype)

# Il dtype del vettore sarà di tipo int visto che sono presenti solo numeri interi


5
5
int64


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [6]:
import numpy as np

a = np.arange(1,10)

b = a[3:6]

# Leggo l'array dall'ultimo elemento con passo -1

c = a[::-1]

dfract = a / c

print(f"{a}, \n{b}, \n{c}, \n{dfract}")

a_list = list(range(1,10))

b_list = a_list[3:6]

c_list = a_list[::-1]

# Utilizzo la list comprehension assieme a zip ( altrimenti una list / list darebbe errore

d_list_fract = [ aelement / belement for aelement, belement in zip(a_list, c_list) ]

print(a_list)
print(b_list)
print(c_list)
print(d_list_fract)

# Da notare che Numpy taglia i float a 8 decimali mentre python arriva a 16 decimali

[1 2 3 4 5 6 7 8 9], 
[4 5 6], 
[9 8 7 6 5 4 3 2 1], 
[0.11111111 0.25       0.42857143 0.66666667 1.         1.5
 2.33333333 4.         9.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.1111111111111111, 0.25, 0.42857142857142855, 0.6666666666666666, 1.0, 1.5, 2.3333333333333335, 4.0, 9.0]
